# Generated by Django 4.1.5 on 2023-01-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='prod_name',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car')], max_length=100),
        ),
    ]
