# Generated by Django 4.1.5 on 2023-02-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_alter_detail_purchase_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='purchase_number',
            field=models.IntegerField(default=0),
        ),
    ]
