# Generated by Django 4.1.5 on 2023-02-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_alter_detail_purchase_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
