# Generated by Django 4.1.5 on 2023-02-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_detail_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='counter',
        ),
        migrations.AlterField(
            model_name='detail',
            name='purchase_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
