# Generated by Django 4.1.5 on 2023-02-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_remove_detail_counter_alter_detail_purchase_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='purchase_number',
        ),
        migrations.AlterField(
            model_name='detail',
            name='invoice_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
