# Generated by Django 4.1.5 on 2023-02-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_remove_detail_purchase_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='puchase_number',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
