# Generated by Django 4.1.5 on 2023-02-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_detail_puchase_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
