# Generated by Django 4.1.5 on 2023-02-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_alter_detail_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='puchase_number',
            new_name='purchase_number',
        ),
    ]
