# Generated by Django 4.1.5 on 2023-02-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_rename_puchase_number_detail_purchase_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='purchase_number',
            field=models.CharField(max_length=200),
        ),
    ]
