# Generated by Django 4.1.5 on 2023-02-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_alter_detail_purchase_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='purchase_number',
        ),
    ]
