# Generated by Django 4.1.5 on 2023-02-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_detail_joined_datetimes_alter_detail_joined_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='joined_datetimes',
            new_name='joined_datetime',
        ),
    ]
